version: "3"
services:
  unpossiblebook:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "4545:4545"
      - "9229:9229"
      - "5433:5432"
    environment:
      - DATABASE_URL=postgresql://unpossible:postgres@postgres/unpossible
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: unpossible
      POSTGRES_DB: unpossible
